version: '3.9'
services:
  db:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    volumes:
      - postgres_db:/var/lib/postgressql/data
    ports:
      - 5432:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  api:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - 5000:${API_PORT}
    env_file:
      - .env
    environment:
      - PORT=${API_PORT}
      - DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    volumes:
      - ./:/app
    depends_on:
      - db

volumes:
  postgres_db:
    driver: local
